name = "ansiColor"
version = "0.1.0"
defaultTargets = ["AnsiColor"]
testDriver = "tests"

[[lean_lib]]
name = "AnsiColor"

[[lean_exe]]
name = "example"
root = "Example"

[[lean_lib]]
name = "tests"
globs = ["Tests.+"]
