# based on https://github.com/leanprover/lean-action/blob/HEAD/README.md

name: Lean Action CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: leanprover/lean-action@v1
        with:
          build: true
          test: true
          check-reservoir-eligibility: true
      - name: Upload Release Artifact
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}
        run: lake upload $TAG
